// Generated by bin/generate_ast.rs

use crate::token::Token;
pub trait Expr: std::fmt::Debug {}

#[derive(Debug, Clone)]
pub struct Binary<'a> {
	pub left: &'a dyn Expr,
	pub operator: Token,
	pub right: &'a dyn Expr,
}
impl Expr for Binary<'_> {}
#[derive(Debug, Clone)]
pub struct Ternary<'a> {
	pub first: &'a dyn Expr,
	pub second: &'a dyn Expr,
	pub third: &'a dyn Expr,
}
impl Expr for Ternary<'_> {}
#[derive(Debug, Clone)]
pub struct Grouping<'a> {
	pub expression: &'a dyn Expr,
}
impl Expr for Grouping<'_> {}
#[derive(Debug, Clone)]
pub struct Literal {
	pub value: String,
}
impl Expr for Literal {}
#[derive(Debug, Clone)]
pub struct Unary<'a> {
	pub operator: Token,
	pub right: &'a dyn Expr,
}
impl Expr for Unary<'_> {}
